version: '2'
services:
  site:
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve --config  _config.yml,_config.docker.yml
    image: jekyll/jekyll:pages
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
